In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

%matplotlib inline
# %matplotlib notebook

plt.rcParams["figure.figsize"] = (10,6)
# plt.rcParams['figure.dpi'] = 100

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

In [3]:
df0= pd.read_csv("a24cumatemiz.csv")

In [4]:
df=df0.copy()

In [5]:
df.shape

(28630, 43)

In [6]:
df.fuel_type.value_counts(dropna=False)

Benzine                     17547
Diesel                       8727
NaN                          1787
LPG/CNG                       359
Electric                      188
Others (Particle filter)       16
Ethanol                         3
Hydrogen                        3
Name: fuel_type, dtype: int64

In [7]:
df.sample(3)

,short_description,make,model,location,price(€),body_type,type,doors,country_version,warranty,mileage,first_registration,gearbox,fuel_type,colour,paint,desc,seller,seats,power,engine_size,gears,co₂-emissions,manufacturer_colour,drivetrain,cylinders,fuel_consumption,empty_weight,general_inspection,full_service_history,non-smoker_vehicle,emission_class,emissions_sticker,upholstery_colour,upholstery,production_date,energy_efficiency_class,co₂-efficiency,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,country
16327,Stepway TCe90 Celebration KAMERA/NAVI,Dacia,Sandero,"Stadtring 7, 33647 Bielefeld, DE",10945,Sedan,Used,5.000,Germany,NaN,"70,753 km",05/2018,Manual,Benzine,Orange,Metallic,"Comfort:, Outside mirror heated, Outside mirro...",Dealer,5.000,66 kW (90 hp),898 cc,NaN,0 g/km (comb.),Taklamakan-Orange,NaN,3.000,NaN,NaN,New,NaN,NaN,Euro 6,4 (Green),Grey,Cloth,2017-01-01,NaN,NaN,"Air conditioning, Armrest, Cruise control, Ele...","Bluetooth, Hands-free equipment, MP3, On-board...","ABS, Central door lock, Daytime running lights...","Roof rack, Summer tyres, Touch screen",Germany
25730,"T3 Aut. Polar+ Luxury, Standkachel, Panoramada...",Volvo,V40 Cross Country,"Celsiusstraat 7, 6902 PV ZEVENAAR, NL",26900,Compact,Used,5.000,Netherlands,NaN,"55,298 km",02/2019,Automatic,Benzine,Brown,Metallic,"Enjoy the space, comfort and freedom that Volv...",Dealer,5.000,112 kW (152 hp),1498 cc,6.000,134 g/km (comb.),Luminous Sand Metallic (bruin,NaN,4.000,5.8 l/100 km (comb.),1360 kg,02/2023,NaN,NaN,Euro 6,NaN,Black,Full leather,2018-01-01,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, Digital radio, On-board computer, R...","ABS, Alarm system, Daytime running lights, Dri...","Alloy wheels (17""), Automatically dimming inte...",Netherlands
10838,1.6 Multijet 130ch Sport TOuvrant Pano GPS Cam...,Fiat,500X,"134 avenue de Colmar, 67100 Strasbourg, FR",27999,Off-Road/Pick-up,Used,5.000,France,NaN,100 km,09/2021,Manual,Diesel,NaN,NaN,"""Electric panoramic roof; Hi-fi beats system; ...",Dealer,5.000,98 kW (133 hp),1598 cc,NaN,135 g/km (comb.),NOIR cinema,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-01,NaN,NaN,"Armrest, Automatic climate control, 2 zones, H...",Sound system,"ABS, Driver-side airbag, Electronic stability ...",Emergency tyre,France

# upholstery doldurma

In [9]:
df["make_model"] = df["make"] + " " + df["model"]

In [10]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "upholstery"] = df.loc[cond2, "upholstery"].fillna(method="ffill").fillna(method="bfill")
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "upholstery"] = df.loc[cond1, "upholstery"].fillna(method="ffill").fillna(method="bfill")
df["upholstery"] = df["upholstery"].fillna(method="ffill").fillna(method="bfill")

In [11]:
df.sample(3)

,short_description,make,model,location,price(€),body_type,type,doors,country_version,warranty,mileage,first_registration,gearbox,fuel_type,colour,paint,desc,seller,seats,power,engine_size,gears,co₂-emissions,manufacturer_colour,drivetrain,cylinders,fuel_consumption,empty_weight,general_inspection,full_service_history,non-smoker_vehicle,emission_class,emissions_sticker,upholstery_colour,upholstery,production_date,energy_efficiency_class,co₂-efficiency,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,country,make_model
14501,"Octavia Combi Ambition 1,0 TSI 85 kW 6-speed m...",Skoda,Octavia,"Rue Du Pont Pavot 23, 5660 Frasnes Lez Couvin...",19950,Station wagon,Used,5.000,Belgium,12 months,"21,272 km",01/2020,Manual,Benzine,Grey,Metallic,Ref 110703],Dealer,5.000,85 kW (116 hp),999 cc,NaN,111 g/km (comb.),Brilliant Silver,NaN,NaN,4.8 l/100 km (comb.),NaN,NaN,Yes,Yes,Euro 6d-TEMP,NaN,Black,Cloth,2019-01-01,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, Digital radio, On-board computer, R...","ABS, Driver-side airbag, Electronic stability ...","Alloy wheels (16""), Roof rack, Voice Control",Belgium,Skoda Octavia
20589,dCi 85 kW (115 CV) E6D N-CONNECTA,Nissan,Qashqai,"AVENIDA CARLOS SAINZ, 15 LEGANES, 28914 MADRI...",20600,Sedan,Used,5.000,Spain,12 months,"25,000 km",11/2020,Manual,Diesel,Silver,NaN,"Cash price: 23290 euros, Gamboa occasion, spec...",Dealer,NaN,85 kW (116 hp),1461 cc,NaN,NaN,Plata,NaN,NaN,3.9 l/100 km (comb.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Full leather,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,Spain,Nissan Qashqai
23188,1.0 EDITION 30 PLUS KAMERA+NAVI+16'' FELGEN,Hyundai,i10,"Bruchstraße 58, 45525 Hattingen, DE",17990,Compact,Pre-registered,5.000,Germany,60 months,12 km,07/2022,Manual,Benzine,White,NaN,"Gears:, Management Gearer, Technology:, Bord C...",Dealer,4.000,49 kW (67 hp),998 cc,5.000,127 g/km (comb.),Atlas white / sol,Front,3.000,4.8 l/100 km (comb.),1068 kg,07/2025,NaN,NaN,Euro 6,NaN,NaN,Cloth,2022-01-01,C,Calculated on basis of measured CO₂-emissions ...,"Air conditioning, Cruise control, Electrical s...","Android Auto, Apple CarPlay, Bluetooth, Digita...","ABS, Alarm system, Central door lock, Daytime ...","Alloy wheels, Touch screen",Germany,Hyundai i10

In [13]:
df.upholstery.replace(["Cloth", "Part leather","Full leather","Velour","alcantara", "Other"], 
                           ["Cloth","Leather","Leather","Cloth","Cloth", "Cloth"], 
                           inplace=True)

In [14]:
df["upholstery"].value_counts(dropna=False)

Cloth      16576
Leather    12054
Name: upholstery, dtype: int64

In [15]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "upholstery_colour"] = df.loc[cond2, "upholstery_colour"].fillna(method="ffill").fillna(method="bfill")
                
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "upholstery_colour"] = df.loc[cond1, "upholstery_colour"].fillna(method="ffill").fillna(method="bfill")            
           
df["upholstery_colour"] = df["upholstery_colour"].fillna(method="ffill").fillna(method="bfill")

In [16]:
df["upholstery_colour"].value_counts(dropna=False)

Black     20311
Grey       4099
Other      2136
Beige       828
Brown       471
Red         266
Blue        264
White       199
Orange       37
Green        12
Yellow        7
Name: upholstery_colour, dtype: int64

In [17]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "energy_efficiency_class"] = df.loc[cond2, "energy_efficiency_class"].fillna(method="ffill").fillna(method="bfill")
                
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "energy_efficiency_class"] = df.loc[cond1, "energy_efficiency_class"].fillna(method="ffill").fillna(method="bfill")            
           
df["energy_efficiency_class"] = df["energy_efficiency_class"].fillna(method="ffill").fillna(method="bfill")

In [18]:
df["energy_efficiency_class"].value_counts(dropna=False)

B       6242
A       5325
C       4557
A+      3059
D       2855
G       1708
E       1689
A+++    1351
A++     1001
F        843
Name: energy_efficiency_class, dtype: int64

In [19]:
df["co₂-efficiency"].fillna("Calculated on basis of measured CO₂-emissions taking into account the mass of the vehicle.", inplace=True)

In [20]:
df["co₂-efficiency"].value_counts(dropna=False)

Calculated on basis of measured CO₂-emissions taking into account the mass of the vehicle.    28630
Name: co₂-efficiency, dtype: int64

In [22]:
df.isnull().sum()

short_description            213
make                           0
model                          0
location                       0
price(€)                       0
body_type                      0
type                           0
doors                        359
country_version               35
warranty                   12846
mileage                        1
first_registration             2
gearbox                      248
fuel_type                   1787
colour                      1724
paint                      14135
desc                        1236
seller                         0
seats                       3125
power                        572
engine_size                 1403
gears                       9676
co₂-emissions              10036
manufacturer_colour         6843
drivetrain                 11737
cylinders                   9778
fuel_consumption            5245
empty_weight               10872
general_inspection         16376
full_service_history       16065
non-smoker_vehicle         17036
emission_class             10771
emissions_sticker          19216
upholstery_colour              0
upholstery                     0
production_date                2
energy_efficiency_class        0
co₂-efficiency                 0
comfort_&_convenience       3197
entertainment_&_media       4986
safety_&_security           3215
extras                      5150
country                        0
make_model                     0
dtype: int64

In [23]:
def simdi(column):
    print("Column Name    : ", column)
    print("-"*40)
    print("Per_of_nulls   : ", "%", round(df[column].isnull().sum()/df.shape[0]*100, 2))
    print("Num_of_nulls   : ", df[column].isnull().sum())
    print("Num_of_uniques : ", df[column].nunique())
    print("-"*40)
    print(df[column].value_counts(dropna = False))

# body_type

In [24]:
simdi("body_type")

Column Name    :  body_type
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  6
----------------------------------------
 Station wagon        5448
 Off-Road/Pick-up     5415
 Compact              5387
 Sedan                5043
 Coupe                4009
 Convertible          3328
Name: body_type, dtype: int64

In [25]:
df.body_type.unique()

array([' Compact ', ' Convertible ', ' Coupe ', ' Off-Road/Pick-up ',
       ' Station wagon ', ' Sedan '], dtype=object)

In [26]:
df.body_type.value_counts(dropna=False)

 Station wagon        5448
 Off-Road/Pick-up     5415
 Compact              5387
 Sedan                5043
 Coupe                4009
 Convertible          3328
Name: body_type, dtype: int64

In [27]:
df.body_type.replace("Other", np.nan, inplace=True)

In [28]:
df.body_type.value_counts(dropna=False)

 Station wagon        5448
 Off-Road/Pick-up     5415
 Compact              5387
 Sedan                5043
 Coupe                4009
 Convertible          3328
Name: body_type, dtype: int64

In [29]:
df.groupby("make_model")["body_type"].value_counts(dropna=False)

make_model      body_type
Dacia            Compact                3
                 Sedan                  1
                 Station wagon          1
Dacia  Break     Station wagon          1
Dacia  Dokker    Station wagon         52
                                     ...
Volvo  XC70      Sedan                  1
Volvo  XC90      Off-Road/Pick-up     199
                 Coupe                  4
                 Station wagon          4
                 Sedan                  3
Name: body_type, Length: 1257, dtype: int64

In [30]:
for group in list(df["make_model"].unique()):
    cond = df["make_model"]==group
    mode = list(df[cond]["body_type"].mode())
    if mode != []:
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df[cond]["body_type"].mode()[0])
    else:
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df["body_type"].mode()[0])

In [31]:
df.groupby("make_model")["body_type"].value_counts(dropna=False)

make_model      body_type
Dacia            Compact                3
                 Sedan                  1
                 Station wagon          1
Dacia  Break     Station wagon          1
Dacia  Dokker    Station wagon         52
                                     ...
Volvo  XC70      Sedan                  1
Volvo  XC90      Off-Road/Pick-up     199
                 Coupe                  4
                 Station wagon          4
                 Sedan                  3
Name: body_type, Length: 1257, dtype: int64

In [32]:
def grouping_fill(df, group_col, col_name):
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[cond][col_name].mode()[0])
        else:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[col_name].mode()[0])
    print("Number of NaN : ",df[col_name].isnull().sum())
    print("------------------")
    print(df.groupby([group_col])[col_name].value_counts(dropna=False))

In [34]:
df.sample(4).T

,7863,4618,20702,3792
short_description,CC 1.6 VTi Première airco cabriolet,GSi 2.0 Automatik Kamera PDC Navi (79),1.2 DIG-T S&S 360 AUTO 115 5P,1.4 T Edition 4x4*Navi*PDC*Tempo*ZVF*Klimaauto...
make,Peugeot,Opel,Nissan,Opel
model,207,Insignia,Qashqai,Mokka
location,"Riezenweg 7, 7071 PV ULFT, NL","Harburger Str. 89, 21680 Stade, DE","C/ GRAN VIA ASIMA, 4, 07009 PALMA, ES","Niederhofheimer Straße 49, 65719 Hofheim Am T..."
price(€),2500,38900,20390,11990
body_type,Convertible,Sedan,Sedan,Off-Road/Pick-up
type,Used,Demonstration,Used,Used
doors,2.000,5.000,5.000,4.000
country_version,Netherlands,Germany,Spain,Germany
warranty,NaN,NaN,12 months,NaN
mileage,"214,113 km","9,482 km","60,184 km","85,100 km"
first_registration,06/2007,09/2020,06/2016,10/2013
gearbox,Manual,Automatic,Automatic,Manual
fuel_type,Benzine,Benzine,Benzine,Benzine
colour,Black,Black,Grey,Blue
paint,Metallic,Metallic,NaN,NaN
desc,"Stylish, a little daring and with excellent ri...","Gearbox:, Automatic, Technology:, ,, on-board ...","Cash price: 20890 euros, *The price includes d...","Vehicle number: S09074GW, Thank you very much ..."
seller,Dealer,Dealer,Dealer,Dealer
seats,4.000,5.000,NaN,5.000
power,88 kW (120 hp),169 kW (230 hp),85 kW (116 hp),103 kW (140 hp)
engine_size,1598 cc,1998 cc,NaN,1364 cc
gears,5.000,8.000,NaN,6.000
co₂-emissions,155 g/km (comb.),161 g/km (comb.),NaN,149 g/km (comb.)
manufacturer_colour,Zwart metallic,Onyx schwarz (metallic),GRIS ANTRACITA,Royalblau/Royal Blue
drivetrain,Front,4WD,NaN,4WD
cylinders,4.000,4.000,NaN,4.000
fuel_consumption,6.5 l/100 km (comb.),7.1 l/100 km (comb.),NaN,6.3 l/100 km (comb.)
empty_weight,1327 kg,NaN,NaN,1394 kg
general_inspection,04/2023,NaN,NaN,03/2024
full_service_history,Yes,Yes,NaN,Yes
non-smoker_vehicle,NaN,Yes,NaN,NaN
emission_class,Euro 4,Euro 6,NaN,Euro 6d-TEMP
emissions_sticker,NaN,NaN,NaN,4 (Green)
upholstery_colour,Other,Black,Black,Black
upholstery,Cloth,Leather,Leather,Cloth
production_date,2006-01-01,2020-01-01,2015-01-01,2013-01-01
energy_efficiency_class,E,C,A,D
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,"Air conditioning, Cruise control, Electrical s...","Air conditioning, Armrest, Automatic climate c...","Cruise control, Tinted windows","Air conditioning, Automatic climate control, 2..."
entertainment_&_media,"CD player, MP3, On-board computer, Radio","Android Auto, Apple CarPlay, Bluetooth, Digita...",NaN,"Bluetooth, CD player, Hands-free equipment, MP..."
safety_&_security,"ABS, Central door lock, Central door lock with...","ABS, Adaptive Cruise Control, Bi-Xenon headlig...","ABS, Fog lights, Side airbag","ABS, Central door lock, Daytime running lights..."
extras,"Alloy wheels (16""), Automatically dimming inte...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,"Alloy wheels, Cargo barrier, E10-enabled, Roof..."
country,Netherlands,Germany,Spain,Germany
make_model,Peugeot 207,Opel Insignia,Nissan Qashqai,Opel Mokka

In [36]:
df['age'] = 2022 - pd.DatetimeIndex(df['production_date']).year

In [37]:
simdi('age')

Column Name    :  age
----------------------------------------
Per_of_nulls   :  % 0.01
Num_of_nulls   :  2
Num_of_uniques :  81
----------------------------------------
4.000       3775
1.000       3367
5.000       3042
2.000       2728
3.000       2580
6.000       2045
7.000       1349
0.000       1190
8.000       1128
9.000        786
11.000       666
10.000       650
12.000       600
13.000       510
15.000       479
16.000       478
14.000       393
17.000       330
18.000       275
19.000       247
21.000       191
22.000       183
20.000       177
23.000       173
24.000       102
25.000        95
27.000        83
26.000        74
28.000        71
31.000        71
29.000        69
30.000        53
32.000        47
56.000        44
33.000        43
50.000        38
57.000        34
36.000        34
35.000        27
58.000        27
55.000        26
34.000        25
45.000        24
54.000        21
52.000        21
44.000        21
40.000        18
51.000        18
53.000        16
39.000        16
38.000        15
37.000        13
48.000        13
59.000        12
47.000        12
43.000        10
61.000         9
46.000         9
49.000         9
60.000         7
63.000         6
68.000         6
65.000         6
42.000         6
41.000         6
69.000         4
93.000         3
91.000         3
NaN            2
67.000         2
86.000         2
64.000         2
123.000        2
62.000         2
70.000         2
89.000         1
-2.000         1
76.000         1
66.000         1
-180.000       1
94.000         1
72.000         1
Name: age, dtype: int64

In [38]:
df.age.fillna("-", inplace=True)

In [49]:
df.groupby("age").mileage.describe()

       count unique        top freq
age
-180.0     1      1   20926 km    1
-2.0       1      1   59629 km    1
0.0     1190    169      10 km  265
1.0     3366   1316      10 km  277
2.0     2728   1934      10 km   20
3.0     2580   1949   51319 km   14
4.0     3775   2611   83991 km   17
5.0     3042   2077  145040 km   34
6.0     2045   1418   29043 km   22
7.0     1349    973  148667 km   17
8.0     1128    723  129214 km   34
9.0      786    599  106263 km   17
10.0     650    494  143281 km   30
11.0     666    468  109065 km   17
12.0     600    460  108000 km    6
13.0     510    369  132539 km    9
14.0     393    291  187500 km    5
15.0     479    334  175259 km    6
16.0     478    319  111242 km   17
17.0     330    264  200000 km    7
18.0     275    221  306504 km    8
19.0     247    191   97876 km   17
20.0     177    144  196000 km    4
21.0     191    155  220320 km    4
22.0     183    131  237737 km    8
23.0     173    141   68000 km    4
24.0     102     86  172000 km    2
25.0      95     80  125000 km    4
26.0      74     65  150000 km    3
27.0      83     76  232600 km    2
28.0      71     63  140000 km    3
29.0      69     65  125000 km    2
30.0      53     48  231225 km    2
31.0      71     63  140000 km    3
32.0      47     44  345000 km    2
33.0      43     38  130000 km    2
34.0      25     22    5700 km    2
35.0      27     24   91700 km    2
36.0      34     32   85000 km    2
37.0      13     13   32183 km    1
38.0      15     15  457379 km    1
39.0      16     16   67100 km    1
40.0      18     17       1 km    2
41.0       6      5  150000 km    2
42.0       6      6   63715 km    1
43.0      10      8  212000 km    2
44.0      21     16  123000 km    3
45.0      24     20  137000 km    2
46.0       9      8  130000 km    2
47.0      12     12       1 km    1
48.0      13     11       1 km    2
49.0       9      9   44444 km    1
50.0      38     33   96200 km    2
51.0      18     16   93128 km    2
52.0      21     20  111111 km    2
53.0      16     14    1000 km    2
54.0      21     19   89525 km    2
55.0      26     25   11231 km    2
56.0      44     40   87562 km    2
57.0      34     32   50000 km    2
58.0      27     23   78915 km    4
59.0      12      9  100000 km    4
60.0       7      6   79900 km    2
61.0       9      6  200000 km    2
62.0       2      2   64200 km    1
63.0       6      5   45740 km    2
64.0       2      2   42736 km    1
65.0       6      6    5650 km    1
66.0       1      1   41170 km    1
67.0       2      2   35000 km    1
68.0       6      4   12100 km    2
69.0       4      3   46000 km    2
70.0       2      2   64000 km    1
72.0       1      1   52466 km    1
76.0       1      1  180000 km    1
86.0       2      1   28000 km    2
89.0       1      1  999999 km    1
91.0       3      3   15000 km    1
93.0       3      3    1233 km    1
94.0       1      1    5000 km    1
123.0      2      2      10 km    1
-          2      2    3856 km    1

In [47]:
df['mileage'] = df['mileage'].str.replace(',', '')

In [48]:
df[df["age"]=="-"]["mileage"].value_counts(dropna=False)

3856 km    1
2494 km    1
Name: mileage, dtype: int64

In [78]:
df.head(3).T

,0,1,2
short_description,CDi,350+,S 4Matic+ 8G-DCT
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz
model,A 160,EQE 350,A 45 AMG
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8..."
price(€),16950,80900,69900
body_type,Compact,Compact,Compact
type,Used,Pre-registered,Used
doors,5.000,4.000,5.000
country_version,Spain,Spain,Spain
warranty,24 months,24 months,12 months
mileage,120200,5000,18900
first_registration,06/2016,06/2022,07/2020
gearbox,Manual,Automatic,Automatic
fuel_type,Diesel,Electric,Benzine
colour,Black,NaN,Grey
paint,Metallic,NaN,NaN
desc,"Cash price: 16950 euros, vehicle with maintena...","Cash price: 88900 euros, Auto Oja S.A. - Offic...","Gray Manufakur Mountingrau Magno, Line/Style A..."
seller,Dealer,Dealer,Dealer
seats,NaN,5.000,5.000
power,NaN,215 kW (292 hp),310 kW (421 hp)
engine_size,NaN,1 cc,1991 cc
gears,NaN,9.000,8.000
co₂-emissions,NaN,0 g/km (comb.),NaN
manufacturer_colour,NaN,Negro Obsidiana,Mountaingrau magno
drivetrain,NaN,NaN,4WD
cylinders,NaN,NaN,4.000
fuel_consumption,NaN,NaN,8.4 l/100 km (comb.)
empty_weight,NaN,NaN,NaN
general_inspection,NaN,NaN,NaN
full_service_history,NaN,NaN,NaN
non-smoker_vehicle,NaN,NaN,NaN
emission_class,NaN,NaN,NaN
emissions_sticker,NaN,NaN,NaN
upholstery_colour,Black,Black,Black
upholstery,Cloth,Leather,Leather
production_date,2015-01-01,2021-01-01,2020-01-01
energy_efficiency_class,A+++,A+++,C
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,NaN,NaN,NaN
entertainment_&_media,NaN,NaN,NaN
safety_&_security,NaN,NaN,NaN
extras,NaN,NaN,NaN
country,Spain,Spain,Spain
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350,Mercedes-Benz A 45 AMG
age,7.000,1.000,2.000

In [77]:
df["mileage"] = df["mileage"].str.replace(' km', '')

In [79]:
df["mileage"] = df["mileage"].astype(float)
age0 = (df["mileage"] < 2000)
age1 = ((df["mileage"] > 2000) & (df["mileage"] < 30000))
age2 = ((df["mileage"] > 30000) & (df["mileage"] < 70000))
age3 = (df["mileage"].astype(float) > 70000)

In [80]:
df.age.value_counts(dropna=False)

4.0       3775
1.0       3367
5.0       3042
2.0       2728
3.0       2580
6.0       2045
7.0       1349
0.0       1190
8.0       1128
9.0        786
11.0       666
10.0       650
12.0       600
13.0       510
15.0       479
16.0       478
14.0       393
17.0       330
18.0       275
19.0       247
21.0       191
22.0       183
20.0       177
23.0       173
24.0       102
25.0        95
27.0        83
26.0        74
28.0        71
31.0        71
29.0        69
30.0        53
32.0        47
56.0        44
33.0        43
50.0        38
57.0        34
36.0        34
35.0        27
58.0        27
55.0        26
34.0        25
45.0        24
54.0        21
52.0        21
44.0        21
40.0        18
51.0        18
53.0        16
39.0        16
38.0        15
37.0        13
48.0        13
59.0        12
47.0        12
43.0        10
61.0         9
46.0         9
49.0         9
60.0         7
63.0         6
68.0         6
65.0         6
42.0         6
41.0         6
69.0         4
93.0         3
91.0         3
-            2
67.0         2
86.0         2
64.0         2
123.0        2
62.0         2
70.0         2
89.0         1
-2.0         1
76.0         1
66.0         1
-180.0       1
94.0         1
72.0         1
Name: age, dtype: int64

In [83]:
df.groupby(["make_model","age"])["price(€)"].mean()

make_model      age
Dacia           0.000    22192.333
                1.000    19515.000
                47.000    9999.000
Dacia  Break    1.000    20500.000
Dacia  Dokker   0.000    16900.000
                            ...
Volvo  XC90     11.000   13900.000
                14.000   11850.000
                15.000    7166.667
                16.000   16990.000
                18.000    6799.000
Name: price(€), Length: 3468, dtype: float64

In [84]:
df.age.replace("-",0, inplace=True)

In [85]:
df.age.value_counts(dropna=False)

4.000       3775
1.000       3367
5.000       3042
2.000       2728
3.000       2580
6.000       2045
7.000       1349
0.000       1192
8.000       1128
9.000        786
11.000       666
10.000       650
12.000       600
13.000       510
15.000       479
16.000       478
14.000       393
17.000       330
18.000       275
19.000       247
21.000       191
22.000       183
20.000       177
23.000       173
24.000       102
25.000        95
27.000        83
26.000        74
28.000        71
31.000        71
29.000        69
30.000        53
32.000        47
56.000        44
33.000        43
50.000        38
36.000        34
57.000        34
35.000        27
58.000        27
55.000        26
34.000        25
45.000        24
54.000        21
52.000        21
44.000        21
40.000        18
51.000        18
53.000        16
39.000        16
38.000        15
37.000        13
48.000        13
59.000        12
47.000        12
43.000        10
61.000         9
46.000         9
49.000         9
60.000         7
68.000         6
63.000         6
65.000         6
42.000         6
41.000         6
69.000         4
93.000         3
91.000         3
67.000         2
86.000         2
64.000         2
62.000         2
70.000         2
123.000        2
-180.000       1
89.000         1
-2.000         1
72.000         1
76.000         1
66.000         1
94.000         1
Name: age, dtype: int64

# mileage

In [86]:
simdi('mileage')

Column Name    :  mileage
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  1
Num_of_uniques :  14183
----------------------------------------
10.000        586
1.000         172
50.000        133
100.000       119
5000.000      118
             ...
141589.000      1
59821.000       1
123500.000      1
29781.000       1
230047.000      1
Name: mileage, Length: 14184, dtype: int64

In [87]:
df.groupby("age")["mileage"].mean()

age
-180.000    20926.000
-2.000      59629.000
0.000        1656.769
1.000        7019.647
2.000       22546.903
3.000       40949.412
4.000       58944.826
5.000       75147.811
6.000       79774.735
7.000       90700.162
8.000      103601.066
9.000      111875.861
10.000     116655.988
11.000     126772.622
12.000     139734.397
13.000     152489.757
14.000     151581.758
15.000     160120.843
16.000     160477.282
17.000     163136.518
18.000     159039.673
19.000     167516.915
20.000     158339.797
21.000     162476.665
22.000     160198.038
23.000     152459.468
24.000     144364.373
25.000     141239.747
26.000     142877.824
27.000     135684.325
28.000     142110.831
29.000     147513.986
30.000     153611.283
31.000     139827.099
32.000     134667.128
33.000     156411.163
34.000     123609.840
35.000     127770.222
36.000     175379.147
37.000      89976.077
38.000     115707.333
39.000      97023.000
40.000     116284.278
41.000     134264.833
42.000      83262.500
43.000     117262.200
44.000     110594.143
45.000     100070.917
46.000      86719.444
47.000      60635.500
48.000      83800.462
49.000      64326.333
50.000      99117.632
51.000      63862.444
52.000      88395.286
53.000      76044.875
54.000      56485.857
55.000     122270.462
56.000      89398.432
57.000      70378.647
58.000      58311.148
59.000      69815.083
60.000      73115.571
61.000     106965.556
62.000      83335.000
63.000      54900.333
64.000      33368.000
65.000      59610.500
66.000      41170.000
67.000      17500.500
68.000      51130.667
69.000      37764.000
70.000      65000.000
72.000      52466.000
76.000     180000.000
86.000      28000.000
89.000     999999.000
91.000      14700.000
93.000      42249.333
94.000       5000.000
123.000     14985.500
Name: mileage, dtype: float64

In [88]:
df.groupby(["make_model","age"])["mileage"].mean()

make_model      age
Dacia           0.000       740.000
                1.000      2376.000
                47.000    59098.000
Dacia  Break    1.000       999.000
Dacia  Dokker   0.000        90.000
                            ...
Volvo  XC90     11.000   221000.000
                14.000   252687.000
                15.000   331666.667
                16.000   148000.000
                18.000   237102.000
Name: mileage, Length: 3466, dtype: float64

In [89]:
df.groupby(["make_model","body_type","age"])["mileage"].mean()

make_model     body_type           age
Dacia           Compact            0.000       110.000
                                   1.000      2376.000
                Sedan              47.000    59098.000
                Station wagon      0.000      2000.000
Dacia  Break    Station wagon      1.000       999.000
                                               ...
Volvo  XC90     Off-Road/Pick-up   18.000   237102.000
                Sedan              2.000     20635.000
                                   3.000     68940.000
                                   5.000     86709.000
                Station wagon      7.000    146775.000
Name: mileage, Length: 5347, dtype: float64

In [90]:
df.mileage.fillna(df.groupby(["body_type","age"]).mileage.transform("mean"),inplace=True)

In [91]:
df.mileage.value_counts(dropna=False)

10.000        586
1.000         172
50.000        133
100.000       119
5000.000      118
             ...
141589.000      1
59821.000       1
123500.000      1
29781.000       1
230047.000      1
Name: mileage, Length: 14184, dtype: int64

In [92]:
df.head(5).T

,0,1,2,3,4
short_description,CDi,350+,S 4Matic+ 8G-DCT,4Matic+ 7G-DCT,200CDI BE Line 4M 7G-DCT
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz
model,A 160,EQE 350,A 45 AMG,A 35 AMG,A 45 AMG
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...","Carrer de Provença, 31 Local, 8029 BARCELONA, ES","CARRIL ARAGONES 4, 30007 CASILLAS, ES"
price(€),16950,80900,69900,46990,16800
body_type,Compact,Compact,Compact,Compact,Compact
type,Used,Pre-registered,Used,Used,Used
doors,5.000,4.000,5.000,5.000,5.000
country_version,Spain,Spain,Spain,Spain,Spain
warranty,24 months,24 months,12 months,12 months,12 months
mileage,120200.000,5000.000,18900.000,18995.000,197000.000
first_registration,06/2016,06/2022,07/2020,01/2020,09/2015
gearbox,Manual,Automatic,Automatic,Automatic,Automatic
fuel_type,Diesel,Electric,Benzine,Benzine,Diesel
colour,Black,NaN,Grey,Yellow,White
paint,Metallic,NaN,NaN,NaN,Metallic
desc,"Cash price: 16950 euros, vehicle with maintena...","Cash price: 88900 euros, Auto Oja S.A. - Offic...","Gray Manufakur Mountingrau Magno, Line/Style A...","Cash price: 48990 euros, Bonus to finance: -2,...","Cash price: 17400 euros, vehicle in perfect co..."
seller,Dealer,Dealer,Dealer,Dealer,Dealer
seats,NaN,5.000,5.000,5.000,5.000
power,NaN,215 kW (292 hp),310 kW (421 hp),225 kW (306 hp),100 kW (136 hp)
engine_size,NaN,1 cc,1991 cc,1991 cc,2143 cc
gears,NaN,9.000,8.000,7.000,7.000
co₂-emissions,NaN,0 g/km (comb.),NaN,NaN,NaN
manufacturer_colour,NaN,Negro Obsidiana,Mountaingrau magno,Amarillo Sol,NaN
drivetrain,NaN,NaN,4WD,4WD,4WD
cylinders,NaN,NaN,4.000,4.000,4.000
fuel_consumption,NaN,NaN,8.4 l/100 km (comb.),7.3 l/100 km (comb.),4.9 l/100 km (comb.)
empty_weight,NaN,NaN,NaN,NaN,1545 kg
general_inspection,NaN,NaN,NaN,NaN,NaN
full_service_history,NaN,NaN,NaN,NaN,NaN
non-smoker_vehicle,NaN,NaN,NaN,NaN,NaN
emission_class,NaN,NaN,NaN,NaN,NaN
emissions_sticker,NaN,NaN,NaN,NaN,NaN
upholstery_colour,Black,Black,Black,Black,Black
upholstery,Cloth,Leather,Leather,Leather,Leather
production_date,2015-01-01,2021-01-01,2020-01-01,2019-01-01,2015-01-01
energy_efficiency_class,A+++,A+++,C,D,C
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,NaN,NaN,NaN,"Air conditioning, Automatic climate control, P...","Air conditioning, Electrical side mirrors, Mul..."
entertainment_&_media,NaN,NaN,NaN,USB,"Bluetooth, CD player, MP3, USB"
safety_&_security,NaN,NaN,NaN,"ABS, Central door lock, Driver-side airbag, El...","ABS, Central door lock, Driver-side airbag, El..."
extras,NaN,NaN,NaN,Sport seats,NaN
country,Spain,Spain,Spain,Spain,Spain
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350,Mercedes-Benz A 45 AMG,Mercedes-Benz A 35 AMG,Mercedes-Benz A 45 AMG
age,7.000,1.000,2.000,3.000,7.000

# type

In [93]:
simdi('type')

Column Name    :  type
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  4
----------------------------------------
 Used               25251
 Demonstration       1433
 Pre-registered      1377
 Employee's car       569
Name: type, dtype: int64

# cylinders

In [104]:
simdi('cylinders')

Column Name    :  cylinders
----------------------------------------
Per_of_nulls   :  % 34.15
Num_of_nulls   :  9778
Num_of_uniques :  12
----------------------------------------
4.000     13068
NaN        9778
3.000      3258
6.000      1013
5.000       799
8.000       539
2.000       103
0.000        35
1.000        21
12.000        8
7.000         6
26.000        1
16.000        1
Name: cylinders, dtype: int64

In [112]:
df["power"] = df["power"].str.split(" ").str[0]

In [114]:
df["power"] = df["power"] .astype(float)

In [115]:
df.groupby("cylinders").power.mean()

cylinders
0.000    136.371
1.000    103.619
2.000     60.480
3.000     76.537
4.000    113.969
5.000    136.508
6.000    234.023
7.000    272.000
8.000    329.955
12.000   364.500
16.000    77.000
26.000    12.000
Name: power, dtype: float64

In [120]:
df["cylinders"].fillna(4, inplace=True)

In [122]:
simdi('gears')

Column Name    :  gears
----------------------------------------
Per_of_nulls   :  % 33.8
Num_of_nulls   :  9676
Num_of_uniques :  11
----------------------------------------
NaN       9676
6.000     8412
5.000     5335
7.000     1738
8.000     1690
1.000      712
9.000      642
4.000      256
10.000     112
0.000       31
3.000       24
2.000        2
Name: gears, dtype: int64

In [123]:
df.gears.fillna("-",inplace=True)

In [125]:
df.groupby(["body_type","make_model","gearbox","gears"])['price(€)'].describe()

                                                     count      mean      std  \
body_type       make_model     gearbox        gears
 Compact        Dacia          Automatic      1.0    1.000 19515.000      NaN
                                              -      2.000 22389.000  127.279
                Dacia  Dokker  Manual         -      1.000 11930.000      NaN
                Dacia  Lodgy   Manual         -      1.000 16500.000      NaN
                Dacia  Logan   Manual         5.0   13.000  9634.769 1719.612
...                                                    ...       ...      ...
 Station wagon  Volvo  XC70    Automatic      8.0    2.000 29390.000    0.000
                                              -     10.000 23864.000 4946.836
                               Manual         6.0    2.000 15950.000    0.000
                Volvo  XC90    Automatic      8.0    2.000 29500.000    0.000
                               Semi-automatic 8.0    2.000 36000.000    0.000

                                                          min       25%  \
body_type       make_model     gearbox        gears
 Compact        Dacia          Automatic      1.0   19515.000 19515.000
                                              -     22299.000 22344.000
                Dacia  Dokker  Manual         -     11930.000 11930.000
                Dacia  Lodgy   Manual         -     16500.000 16500.000
                Dacia  Logan   Manual         5.0    6250.000  8695.000
...                                                       ...       ...
 Station wagon  Volvo  XC70    Automatic      8.0   29390.000 29390.000
                                              -     15990.000 22900.000
                               Manual         6.0   15950.000 15950.000
                Volvo  XC90    Automatic      8.0   29500.000 29500.000
                               Semi-automatic 8.0   36000.000 36000.000

                                                          50%       75%  \
body_type       make_model     gearbox        gears
 Compact        Dacia          Automatic      1.0   19515.000 19515.000
                                              -     22389.000 22434.000
                Dacia  Dokker  Manual         -     11930.000 11930.000
                Dacia  Lodgy   Manual         -     16500.000 16500.000
                Dacia  Logan   Manual         5.0    9399.000 10900.000
...                                                       ...       ...
 Station wagon  Volvo  XC70    Automatic      8.0   29390.000 29390.000
                                              -     23490.000 26950.000
                               Manual         6.0   15950.000 15950.000
                Volvo  XC90    Automatic      8.0   29500.000 29500.000
                               Semi-automatic 8.0   36000.000 36000.000

                                                          max
body_type       make_model     gearbox        gears
 Compact        Dacia          Automatic      1.0   19515.000
                                              -     22479.000
                Dacia  Dokker  Manual         -     11930.000
                Dacia  Lodgy   Manual         -     16500.000
                Dacia  Logan   Manual         5.0   11950.000
...                                                       ...
 Station wagon  Volvo  XC70    Automatic      8.0   29390.000
                                              -     29990.000
                               Manual         6.0   15950.000
                Volvo  XC90    Automatic      8.0   29500.000
                               Semi-automatic 8.0   36000.000

[3181 rows x 8 columns]

In [133]:
df.gears.replace([0,1,2,3,4,9,10,"-"],np.nan, inplace=True)

In [134]:
df.gears.value_counts(dropna=False)

6.000    13993
5.000     8048
7.000     3081
8.000     2780
NaN        728
Name: gears, dtype: int64

In [135]:
df.groupby(["body_type","make_model","gearbox"]).gears.count()

body_type        make_model                 gearbox
 Compact         Dacia                      Automatic          3
                 Dacia  Dokker              Manual             1
                 Dacia  Lodgy               Manual             1
                 Dacia  Logan               Manual            13
                 Dacia  Sandero             Automatic         14
                                                              ..
 Station wagon   Volvo  V90 Cross Country   Automatic         80
                 Volvo  XC70                Automatic         24
                                            Manual             2
                 Volvo  XC90                Automatic          2
                                            Semi-automatic     2
Name: gears, Length: 1682, dtype: int64

In [136]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        for group3 in list(df["gearbox"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2) & (df["gearbox"]==group3)
            mode = list(df[cond]["gears"].mode())
            if mode != []:
                df.loc[cond, "gears"] = df.loc[cond, "gears"].fillna(df[cond]["gears"].mode()[0])
            else:
                df.loc[cond, "gears"] = df.loc[cond, "gears"].fillna(df["gears"].mode()[0])

In [138]:
df['gears'].fillna(5, inplace=True)

In [139]:
df.gears.value_counts(dropna=False)

6.000    14494
5.000     8265
7.000     3089
8.000     2782
Name: gears, dtype: int64

In [155]:
df2=df0.copy()

# extras

In [161]:
df['extras']=df2['extras']

In [162]:
simdi('extras')

Column Name    :  extras
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  9360
----------------------------------------
Alloy wheels                                                                                                                                                                                6506
Alloy wheels, Sport seats                                                                                                                                                                    490
Roof rack                                                                                                                                                                                    466
Alloy wheels, Roof rack                                                                                                                                                                      386
Alloy wheels, Touch screen                                                                                                                                                                   280
                                                                                                                                                                                            ...
Alloy wheels, Awning, Catalytic Converter, Emergency tyre repair kit, Headlight washer system, Range extender, Sport package, Sport seats, Sport suspension, Summer tyres, Voice Control       1
Alloy wheels, Automatically dimming interior mirror, Emergency tyre repair kit, Sport package, Sport seats, Sport suspension                                                                   1
Alloy wheels (19"), Headlight washer system, Sport package, Sport seats, Sport suspension                                                                                                      1
Alloy wheels (15"), Sport package, Sport seats, Sport suspension                                                                                                                               1
Alloy wheels, Automatically dimming interior mirror, Ski bag, Trailer hitch                                                                                                                    1
Name: extras, Length: 9360, dtype: int64

In [142]:
df["extras"]=df["extras"].apply(ext).str[0]

In [ ]:
df.Extras.value_counts(dropna=False)

In [159]:
df2["make_model"] = df2["make"] + " " + df2["model"]
for group1 in list(df2["make_model"].unique()):
    for group2 in list(df2["body_type"].unique()):
            cond = (df2["make_model"]==group1) & (df2["body_type"]==group2)
            mode = list(df2[cond]["extras"].mode())
            if mode != []:
                df2.loc[cond, "extras"] = df2.loc[cond, "extras"].fillna(df2[cond]["extras"].mode()[0])
            else:
                df2.loc[cond, "extras"] = df2.loc[cond, "extras"].fillna(df2["extras"].mode()[0])

In [163]:
df.sample(3).T

,190,17697,3991
short_description,Edition Navigatie 4U3,GRJ 79 4.0 V6 SPERRE WINDE AHK,B SpTourer Business INNO 4x4 OPC AUTOMATIK NAV...
make,Mercedes-Benz,Toyota,Opel
model,A 180,Land Cruiser,Insignia
location,"Zuiderzeestraatweg 469, 8091 CM WEZEP, NL","Julius-Bausch-Str. 43, 73431 Aalen, DE","Karl-Heinz-Klingen-Straße 106, 46539 Dinslake..."
price(€),13950,66950,22950
body_type,Compact,Off-Road/Pick-up,Station wagon
type,Used,Pre-registered,Used
doors,5.000,4.000,5.000
country_version,Netherlands,Germany,Germany
warranty,12 months,NaN,NaN
mileage,133773.000,50.000,112877.000
first_registration,08/2013,07/2022,02/2018
gearbox,Manual,Manual,Automatic
fuel_type,Benzine,Benzine,Diesel
colour,Black,Grey,Blue
paint,NaN,Metallic,NaN
desc,They say that Germans have little humor. Yet t...,Toyota Land Cruiser GRJ 79 DC LX 4.0 V6 5-spee...,"Gear:, Automatic, Technology:, All-wheel drive..."
seller,Dealer,Dealer,Dealer
seats,5.000,6.000,5.000
power,90.000,167.000,154.000
engine_size,1595 cc,3956 cc,1956 cc
gears,6.000,6.000,8.000
co₂-emissions,120 g/km (comb.),336 g/km (comb.),188 g/km (comb.)
manufacturer_colour,Zwart,1G3 marlingrau,Tiefsee blau
drivetrain,Front,4WD,4WD
cylinders,4.000,4.000,4.000
fuel_consumption,5.2 l/100 km (comb.),15.6 l/100 km (comb.),6.9 l/100 km (comb.)
empty_weight,1260 kg,NaN,NaN
general_inspection,01/2023,New,NaN
full_service_history,Yes,NaN,Yes
non-smoker_vehicle,NaN,Yes,Yes
emission_class,Euro 6,Euro 6,Euro 6
emissions_sticker,NaN,4 (Green),NaN
upholstery_colour,Brown,Grey,Black
upholstery,Leather,Cloth,Leather
production_date,2013-01-01,2022-01-01,2017-01-01
energy_efficiency_class,E,G,D
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,"Air conditioning, Armrest, Cruise control, Ele...","Air conditioning, Electrical side mirrors, Lea...","Air conditioning, Automatic climate control, A..."
entertainment_&_media,"Bluetooth, CD player, Radio",Radio,"Android Auto, Apple CarPlay, Bluetooth, Digita..."
safety_&_security,"ABS, Alarm system, Bi-Xenon headlights, Centra...","ABS, Central door lock, Driver-side airbag, El...","ABS, Adaptive Cruise Control, Blind spot monit..."
extras,Trailer hitch,"All season tyres, Alloy wheels, Spare tyre, Tr...","Alloy wheels, Shift paddles, Sport package, Sp..."
country,Netherlands,Germany,Germany
make_model,Mercedes-Benz A 180,Toyota Land Cruiser,Opel Insignia
age,9.000,0.000,5.000

In [164]:
simdi('power')

Column Name    :  power
----------------------------------------
Per_of_nulls   :  % 2.0
Num_of_nulls   :  572
Num_of_uniques :  351
----------------------------------------
110.000    1992
96.000     1356
88.000     1182
81.000     1166
66.000     1110
           ...
746.000       1
570.000       1
471.000       1
179.000       1
26.000        1
Name: power, Length: 352, dtype: int64

In [165]:
df.power.fillna("-", inplace=True)

In [167]:
df.groupby(["body_type", "make_model", "power"])['price(€)'].describe()

                                        count      mean      std       min  \
body_type       make_model     power
 Compact        Dacia          33.000   3.000 21431.000 1661.744 19515.000
                Dacia  Dokker  66.000   1.000 11930.000      NaN 11930.000
                Dacia  Lodgy   85.000   1.000 16500.000      NaN 16500.000
                Dacia  Logan   54.000   1.000 10234.000      NaN 10234.000
                               55.000   8.000  9440.375 1857.060  6250.000
...                                       ...       ...      ...       ...
 Station wagon  Volvo  XC70    162.000  2.000 23490.000    0.000 23490.000
                               163.000  4.000 24947.500 2364.249 22900.000
                               165.000  2.000 15990.000    0.000 15990.000
                               180.000  2.000 26950.000    0.000 26950.000
                Volvo  XC90    165.000  4.000 32750.000 3752.777 29500.000

                                             25%       50%       75%       max
body_type       make_model     power
 Compact        Dacia          33.000  20907.000 22299.000 22389.000 22479.000
                Dacia  Dokker  66.000  11930.000 11930.000 11930.000 11930.000
                Dacia  Lodgy   85.000  16500.000 16500.000 16500.000 16500.000
                Dacia  Logan   54.000  10234.000 10234.000 10234.000 10234.000
                               55.000   8924.000  9399.000 10662.500 11727.000
...                                          ...       ...       ...       ...
 Station wagon  Volvo  XC70    162.000 23490.000 23490.000 23490.000 23490.000
                               163.000 22900.000 24947.500 26995.000 26995.000
                               165.000 15990.000 15990.000 15990.000 15990.000
                               180.000 26950.000 26950.000 26950.000 26950.000
                Volvo  XC90    165.000 29500.000 32750.000 36000.000 36000.000

[5034 rows x 8 columns]

In [168]:
df.power.replace("-", np.nan, inplace=True)

In [169]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["power"].mode())
            if mode != []:
                df.loc[cond, "power"] = df.loc[cond, "power"].fillna(df[cond]["power"].mode()[0])
            else:
                df.loc[cond, "power"] = df.loc[cond, "power"].fillna(df["power"].mode()[0])

In [170]:
df.power.value_counts(dropna=False)

110.000    2029
96.000     1426
88.000     1201
81.000     1185
66.000     1149
           ...
570.000       1
471.000       1
179.000       1
284.000       1
26.000        1
Name: power, Length: 351, dtype: int64

In [171]:
simdi('general_inspection')

Column Name    :  general_inspection
----------------------------------------
Per_of_nulls   :  % 57.2
Num_of_nulls   :  16376
Num_of_uniques :  91
----------------------------------------
NaN        16376
New         5883
05/2023      286
08/2023      280
03/2023      268
06/2023      266
04/2023      262
09/2023      255
07/2023      254
06/2024      216
05/2024      212
01/2023      210
02/2023      209
03/2024      207
07/2024      203
08/2024      187
09/2024      182
11/2023      176
01/2024      164
02/2024      163
04/2024      162
12/2023      160
12/2022      159
10/2023      155
06/2025      147
11/2022      131
08/2025      122
07/2025      110
09/2022       96
03/2025       95
05/2025       93
10/2022       90
04/2025       89
01/2025       75
02/2025       66
09/2025       65
10/2024       64
08/2022       64
12/2024       61
11/2024       50
06/2022       42
07/2022       41
04/2022       34
03/2022       25
05/2022       22
10/2021       17
11/2021       11
01/2022       10
07/2021       10
09/2021        8
08/2021        7
12/2021        7
02/2022        6
05/2026        5
07/2020        5
10/2025        4
05/2021        4
06/2026        4
12/2019        4
06/2021        3
01/2021        3
11/2020        3
04/2026        3
02/2021        2
02/2026        2
12/2025        2
09/2026        2
01/2026        2
12/2020        2
07/2026        2
08/2026        2
02/2027        2
06/2020        2
12/2017        1
10/2020        1
01/2020        1
04/2020        1
10/2019        1
05/2018        1
09/2020        1
07/2019        1
05/2020        1
08/2019        1
03/2026        1
11/2019        1
01/2018        1
07/2017        1
09/2017        1
08/2013        1
08/2020        1
08/2018        1
03/2021        1
Name: general_inspection, dtype: int64

In [176]:
df.general_inspection.fillna("New", inplace=True)

In [177]:
simdi('general_inspection')

Column Name    :  general_inspection
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  91
----------------------------------------
New        22259
05/2023      286
08/2023      280
03/2023      268
06/2023      266
04/2023      262
09/2023      255
07/2023      254
06/2024      216
05/2024      212
01/2023      210
02/2023      209
03/2024      207
07/2024      203
08/2024      187
09/2024      182
11/2023      176
01/2024      164
02/2024      163
04/2024      162
12/2023      160
12/2022      159
10/2023      155
06/2025      147
11/2022      131
08/2025      122
07/2025      110
09/2022       96
03/2025       95
05/2025       93
10/2022       90
04/2025       89
01/2025       75
02/2025       66
09/2025       65
10/2024       64
08/2022       64
12/2024       61
11/2024       50
06/2022       42
07/2022       41
04/2022       34
03/2022       25
05/2022       22
10/2021       17
11/2021       11
01/2022       10
07/2021       10
09/2021        8
08/2021        7
12/2021        7
02/2022        6
05/2026        5
07/2020        5
10/2025        4
05/2021        4
06/2026        4
12/2019        4
06/2021        3
01/2021        3
11/2020        3
04/2026        3
02/2021        2
02/2026        2
12/2025        2
09/2026        2
01/2026        2
12/2020        2
07/2026        2
08/2026        2
02/2027        2
06/2020        2
12/2017        1
10/2020        1
01/2020        1
04/2020        1
10/2019        1
05/2018        1
09/2020        1
07/2019        1
05/2020        1
08/2019        1
03/2026        1
11/2019        1
01/2018        1
07/2017        1
09/2017        1
08/2013        1
08/2020        1
08/2018        1
03/2021        1
Name: general_inspection, dtype: int64

# paint

In [178]:
simdi('paint')

Column Name    :  paint
----------------------------------------
Per_of_nulls   :  % 49.37
Num_of_nulls   :  14135
Num_of_uniques :  2
----------------------------------------
Metallic     14494
NaN          14135
Uni/basic        1
Name: paint, dtype: int64

In [179]:
df.paint.fillna("-", inplace=True)

In [180]:
df.groupby(["make_model", "paint"])['price(€)'].describe()

                          count      mean       std       min       25%  \
make_model     paint
Dacia          -          1.000  9999.000       NaN  9999.000  9999.000
               Metallic   4.000 21523.000  1369.228 19515.000 21228.000
Dacia  Break   -          1.000 20500.000       NaN 20500.000 20500.000
Dacia  Dokker  -         39.000 12834.026  3049.146  3890.000 11814.500
               Metallic  17.000 14069.235  3499.122  7200.000 12490.000
...                         ...       ...       ...       ...       ...
Volvo  XC60    Metallic 273.000 44497.407 15843.429 10200.000 34490.000
Volvo  XC70    -         12.000 17748.333  6615.660  8900.000 13500.000
               Metallic  17.000 22348.824  6441.065  8750.000 22490.000
Volvo  XC90    -         59.000 44696.373 19628.308  6400.000 33990.000
               Metallic 151.000 54316.768 19300.574  7500.000 44195.000

                              50%       75%       max
make_model     paint
Dacia          -         9999.000  9999.000  9999.000
               Metallic 22049.000 22344.000 22479.000
Dacia  Break   -        20500.000 20500.000 20500.000
Dacia  Dokker  -        13500.000 14845.000 17250.000
               Metallic 13680.000 15980.000 19997.000
...                           ...       ...       ...
Volvo  XC60    Metallic 44900.000 54880.000 83890.000
Volvo  XC70    -        17400.000 19900.000 29390.000
               Metallic 23490.000 26950.000 29990.000
Volvo  XC90    -        42790.000 55900.000 83900.000
               Metallic 50990.000 64990.000 97450.000

[1035 rows x 8 columns]

In [181]:
df.paint.replace("-", np.nan, inplace=True)

In [182]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        df.loc[cond2, "paint"] = df.loc[cond2, "paint"].fillna(method="ffill").fillna(method="bfill")
                
for group1 in list(df["make_model"].unique()):
    cond1 = df["make_model"]==group1
    df.loc[cond1, "paint"] = df.loc[cond1, "paint"].fillna(method="ffill").fillna(method="bfill")            
           
df["paint"] = df["paint"].fillna(method="ffill").fillna(method="bfill")

In [184]:
df.paint.value_counts(dropna=False)

Metallic     28622
Uni/basic        8
Name: paint, dtype: int64

In [197]:
df.head(1).T

                                                                         0
short_description                                                      CDi
make                                                         Mercedes-Benz
model                                                               A 160
location                 P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SAN...
price(€)                                                             16950
body_type                                                         Compact
type                                                                 Used
doors                                                                5.000
country_version                                                      Spain
warranty                                                        24 months
mileage                                                         120200.000
first_registration                                                 06/2016
gearbox                                                             Manual
fuel_type                                                           Diesel
colour                                                               Black
paint                                                             Metallic
desc                     Cash price: 16950 euros, vehicle with maintena...
seller                                                              Dealer
seats                                                                5.000
power                                                               75.000
engine_size                                                        1595 cc
gears                                                                5.000
co₂-emissions                                                          NaN
manufacturer_colour                                                    NaN
drivetrain                                                             NaN
cylinders                                                            4.000
fuel_consumption                                                       NaN
empty_weight                                                           NaN
general_inspection                                                     New
full_service_history                                                   NaN
non-smoker_vehicle                                                     NaN
emission_class                                                         NaN
emissions_sticker                                                      NaN
upholstery_colour                                                    Black
upholstery                                                           Cloth
production_date                                                 2015-01-01
energy_efficiency_class                                               A+++
co₂-efficiency           Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience                                                  NaN
entertainment_&_media                                                  NaN
safety_&_security                                                      NaN
extras                                                        Alloy wheels
country                                                              Spain
make_model                                           Mercedes-Benz  A 160
age                                                                  7.000

# seats

In [189]:
simdi('seats')

Column Name    :  seats
----------------------------------------
Per_of_nulls   :  % 10.92
Num_of_nulls   :  3125
Num_of_uniques :  11
----------------------------------------
5.000     18308
4.000      5390
NaN        3125
2.000      1186
7.000       488
8.000        43
9.000        35
3.000        25
6.000        12
0.000         9
1.000         7
17.000        2
Name: seats, dtype: int64

In [190]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["seats"].mode())
            if mode != []:
                df.loc[cond, "seats"] = df.loc[cond, "seats"].fillna(df[cond]["seats"].mode()[0])
            else:
                df.loc[cond, "seats"] = df.loc[cond, "seats"].fillna(df["seats"].mode()[0])

In [191]:
df.seats.value_counts(dropna=False)

5.000     20743
4.000      5957
2.000      1261
7.000       535
8.000        44
9.000        35
3.000        25
6.000        12
0.000         9
1.000         7
17.000        2
Name: seats, dtype: int64

# doors

In [185]:
simdi('doors')

Column Name    :  doors
----------------------------------------
Per_of_nulls   :  % 1.25
Num_of_nulls   :  359
Num_of_uniques :  6
----------------------------------------
5.000    17481
2.000     5523
4.000     3001
3.000     2259
NaN        359
6.000        5
1.000        2
Name: doors, dtype: int64

In [186]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["doors"].mode())
            if mode != []:
                df.loc[cond, "doors"] = df.loc[cond, "doors"].fillna(df[cond]["doors"].mode()[0])
            else:
                df.loc[cond, "doors"] = df.loc[cond, "doors"].fillna(df["doors"].mode()[0])

In [187]:
df.doors.value_counts(dropna=False)

5.000    17645
2.000     5664
4.000     3010
3.000     2304
6.000        5
1.000        2
Name: doors, dtype: int64

# engine_size

In [193]:
simdi('engine_size')

Column Name    :  engine_size
----------------------------------------
Per_of_nulls   :  % 4.9
Num_of_nulls   :  1403
Num_of_uniques :  467
----------------------------------------
1598 cc    2099
999 cc     2068
1969 cc    1929
NaN        1403
1461 cc    1110
           ...
2753 cc       1
2495 cc       1
200 cc        1
3224 cc       1
2473 cc       1
Name: engine_size, Length: 468, dtype: int64

In [195]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["engine_size"].mode())
            if mode != []:
                df.loc[cond, "engine_size"] = df.loc[cond, "engine_size"].fillna(df[cond]["engine_size"].mode()[0])
            else:
                df.loc[cond, "engine_size"] = df.loc[cond, "engine_size"].fillna(df["engine_size"].mode()[0])

In [196]:
df.engine_size.value_counts(dropna=False)

1598 cc    2383
999 cc     2143
1969 cc    1957
1461 cc    1144
1998 cc    1056
           ...
2565 cc       1
2573 cc       1
3059 cc       1
2568 cc       1
2473 cc       1
Name: engine_size, Length: 467, dtype: int64

In [198]:
simdi('co₂-emissions')

Column Name    :  co₂-emissions
----------------------------------------
Per_of_nulls   :  % 35.05
Num_of_nulls   :  10036
Num_of_uniques :  347
----------------------------------------
NaN                  10036
0 g/km (comb.)        1038
119 g/km (comb.)       393
124 g/km (comb.)       340
129 g/km (comb.)       319
                     ...
7 g/km (comb.)           1
80 g/km (comb.)          1
196  g/km (comb.)        1
100  g/km (comb.)        1
53 g/km (comb.)          1
Name: co₂-emissions, Length: 348, dtype: int64

In [200]:
df["co₂-emissions"].fillna("-",inplace=True)

In [201]:
df["co₂-emissions"].replace("-", np.nan, inplace=True)

In [202]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["co₂-emissions"].mode())
            if mode != []:
                df.loc[cond, "co₂-emissions"] = df.loc[cond, "co₂-emissions"].fillna(df[cond]["co₂-emissions"].mode()[0])
            else:
                df.loc[cond, "co₂-emissions"] = df.loc[cond, "co₂-emissions"].fillna(df["co₂-emissions"].mode()[0])

In [214]:
df.head(1).T

                                                                         0
short_description                                                      CDi
make                                                         Mercedes-Benz
model                                                               A 160
location                 P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SAN...
price(€)                                                             16950
body_type                                                         Compact
type                                                                 Used
doors                                                                5.000
country_version                                                      Spain
warranty                                                        24 months
mileage                                                         120200.000
first_registration                                                 06/2016
gearbox                                                             Manual
fuel_type                                                           Diesel
colour                                                               Black
paint                                                             Metallic
desc                     Cash price: 16950 euros, vehicle with maintena...
seller                                                              Dealer
seats                                                                5.000
power                                                               75.000
engine_size                                                        1595 cc
gears                                                                5.000
co₂-emissions                                             126 g/km (comb.)
manufacturer_colour                                         Grijs metallic
drivetrain                                                          Front
cylinders                                                            4.000
fuel_consumption                                                       NaN
empty_weight                                                           NaN
general_inspection                                                     New
full_service_history                                                   NaN
non-smoker_vehicle                                                     NaN
emission_class                                                         NaN
emissions_sticker                                                      NaN
upholstery_colour                                                    Black
upholstery                                                           Cloth
production_date                                                 2015-01-01
energy_efficiency_class                                               A+++
co₂-efficiency           Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience                                                  NaN
entertainment_&_media                                                  NaN
safety_&_security                                                      NaN
extras                                                        Alloy wheels
country                                                              Spain
make_model                                           Mercedes-Benz  A 160
age                                                                  7.000

In [205]:
simdi('manufacturer_colour')

Column Name    :  manufacturer_colour
----------------------------------------
Per_of_nulls   :  % 23.9
Num_of_nulls   :  6843
Num_of_uniques :  4963
----------------------------------------
NaN                               6843
Blanco                            1235
Gris                               671
Azul                               552
Negro                              546
                                  ...
Colore esterno (snowflake whit       1
Pompeigraumetallic                   1
Cararragrau                          1
ICE WHITE (wit metallic)             1
Denim Blue metallic (blauw met       1
Name: manufacturer_colour, Length: 4964, dtype: int64

In [206]:
df["manufacturer_colour"].fillna("-",inplace=True)
df["manufacturer_colour"].replace("-", np.nan, inplace=True)

In [207]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["manufacturer_colour"].mode())
            if mode != []:
                df.loc[cond, "manufacturer_colour"] = df.loc[cond, "manufacturer_colour"].fillna(df[cond]["manufacturer_colour"].mode()[0])
            else:
                df.loc[cond, "manufacturer_colour"] = df.loc[cond, "manufacturer_colour"].fillna(df["manufacturer_colour"].mode()[0])

In [208]:
df["manufacturer_colour"].value_counts(dropna=False)

Blanco                            2610
Grijs metallic                    1094
Gris                               904
Azul                               725
Rojo                               699
                                  ...
718 SCHWARZ                          1
Verde Foresta (groen metallic)       1
Galato Weiß                          1
612 SILBER                           1
Denim Blue metallic (blauw met       1
Name: manufacturer_colour, Length: 4962, dtype: int64

In [210]:
simdi('drivetrain')

Column Name    :  drivetrain
----------------------------------------
Per_of_nulls   :  % 41.0
Num_of_nulls   :  11737
Num_of_uniques :  3
----------------------------------------
 Front     12066
NaN        11737
 4WD        3252
 Rear       1575
Name: drivetrain, dtype: int64

In [211]:
df["drivetrain"].fillna("-",inplace=True)
df["drivetrain"].replace("-", np.nan, inplace=True)

In [212]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["drivetrain"].mode())
            if mode != []:
                df.loc[cond, "drivetrain"] = df.loc[cond, "drivetrain"].fillna(df[cond]["drivetrain"].mode()[0])
            else:
                df.loc[cond, "drivetrain"] = df.loc[cond, "drivetrain"].fillna(df["drivetrain"].mode()[0])

In [213]:
df["drivetrain"].value_counts(dropna=False)

 Front     21603
 4WD        4235
 Rear       2792
Name: drivetrain, dtype: int64

In [215]:
simdi('fuel_consumption')

Column Name    :  fuel_consumption
----------------------------------------
Per_of_nulls   :  % 18.32
Num_of_nulls   :  5245
Num_of_uniques :  218
----------------------------------------
NaN                       5245
5 l/100 km (comb.)         818
4.9 l/100 km (comb.)       809
4.5 l/100 km (comb.)       690
5.1 l/100 km (comb.)       639
                          ...
6.5 kg/100 km (comb.)        1
4 kg/100 km (comb.)          1
7 l/100 km (city)            1
4.9 l/100 km (country)       1
9 l/100 km (country)         1
Name: fuel_consumption, Length: 219, dtype: int64

In [227]:
df["fuel_consumption"] = df.fuel_consumption.str.extract("(\d+\.\d+|\d+)", expand=False)

In [228]:
df["fuel_consumption"].fillna("-",inplace=True)
df["fuel_consumption"].replace("-", np.nan, inplace=True)

In [229]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["fuel_consumption"].mode())
            if mode != []:
                df.loc[cond, "fuel_consumption"] = df.loc[cond, "fuel_consumption"].fillna(df[cond]["fuel_consumption"].mode()[0])
            else:
                df.loc[cond, "fuel_consumption"] = df.loc[cond, "fuel_consumption"].fillna(df["fuel_consumption"].mode()[0])

In [230]:
df["fuel_consumption"].value_counts(dropna=False)

5       1828
4.9      996
4.5      899
0        818
4.7      756
        ...
0.5        1
16         1
57         1
15.9       1
15.5       1
Name: fuel_consumption, Length: 161, dtype: int64

In [249]:
df.head(2).T

,0,1
short_description,CDi,350+
make,Mercedes-Benz,Mercedes-Benz
model,A 160,EQE 350
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES"
price(€),16950,80900
body_type,Compact,Compact
type,Used,Pre-registered
doors,5.000,4.000
country_version,Spain,Spain
warranty,24 months,24 months
mileage,120200.000,5000.000
first_registration,06/2016,06/2022
gearbox,Manual,Automatic
fuel_type,Diesel,Electric
colour,Black,NaN
paint,Metallic,Metallic
desc,"Cash price: 16950 euros, vehicle with maintena...","Cash price: 88900 euros, Auto Oja S.A. - Offic..."
seller,Dealer,Dealer
seats,5.000,5.000
power,75.000,215.000
engine_size,1595 cc,1 cc
gears,5.000,6.000
co₂-emissions,126 g/km (comb.),0 g/km (comb.)
manufacturer_colour,Grijs metallic,Negro Obsidiana
drivetrain,Front,Front
cylinders,4.000,4.000
fuel_consumption,5.4,5
empty_weight,1270 kg,1395 kg
general_inspection,New,New
emission_class,Euro 6,Euro 6
emissions_sticker,1 (No sticker),4 (Green)
upholstery_colour,Black,Black
upholstery,Cloth,Leather
production_date,2015-01-01,2021-01-01
energy_efficiency_class,A+++,A+++
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,NaN,NaN
entertainment_&_media,NaN,NaN
safety_&_security,NaN,NaN
extras,Alloy wheels,Alloy wheels
country,Spain,Spain
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350
age,7.000,1.000

In [232]:
simdi('empty_weight')

Column Name    :  empty_weight
----------------------------------------
Per_of_nulls   :  % 37.97
Num_of_nulls   :  10872
Num_of_uniques :  1218
----------------------------------------
NaN        10872
1395 kg      233
1055 kg      224
1423 kg      216
1165 kg      200
           ...
1877 kg        1
1011 kg        1
1069 kg        1
983 kg         1
1391 kg        1
Name: empty_weight, Length: 1219, dtype: int64

In [233]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["empty_weight"].mode())
            if mode != []:
                df.loc[cond, "empty_weight"] = df.loc[cond, "empty_weight"].fillna(df[cond]["empty_weight"].mode()[0])
            else:
                df.loc[cond, "empty_weight"] = df.loc[cond, "empty_weight"].fillna(df["empty_weight"].mode()[0])

In [234]:
df["empty_weight"].value_counts(dropna=False)

1395 kg    1000
1320 kg     631
1055 kg     506
1280 kg     487
1165 kg     392
           ...
1069 kg       1
983 kg        1
695 kg        1
895 kg        1
1391 kg       1
Name: empty_weight, Length: 1218, dtype: int64

In [236]:
simdi('full_service_history')

Column Name    :  full_service_history
----------------------------------------
Per_of_nulls   :  % 56.11
Num_of_nulls   :  16065
Num_of_uniques :  1
----------------------------------------
NaN    16065
Yes    12565
Name: full_service_history, dtype: int64

In [238]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["full_service_history"].mode())
            if mode != []:
                df.loc[cond, "full_service_history"] = df.loc[cond, "full_service_history"].fillna(df[cond]["full_service_history"].mode()[0])
            else:
                df.loc[cond, "full_service_history"] = df.loc[cond, "full_service_history"].fillna(df["full_service_history"].mode()[0])

In [239]:
df["full_service_history"].value_counts(dropna=False)

Yes    28630
Name: full_service_history, dtype: int64

In [240]:
df.drop("full_service_history", axis=1, inplace=True)

In [241]:
df.drop("non-smoker_vehicle", axis=1, inplace=True)

In [242]:
simdi('emission_class')

Column Name    :  emission_class
----------------------------------------
Per_of_nulls   :  % 37.62
Num_of_nulls   :  10771
Num_of_uniques :  9
----------------------------------------
NaN             10771
Euro 6           6418
Euro 6d-TEMP     3399
Euro 6d          2858
Euro 5           2389
Euro 4           1743
Euro 3            523
Euro 2            217
Euro 1            172
Euro 6c           140
Name: emission_class, dtype: int64

In [243]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["emission_class"].mode())
            if mode != []:
                df.loc[cond, "emission_class"] = df.loc[cond, "emission_class"].fillna(df[cond]["emission_class"].mode()[0])
            else:
                df.loc[cond, "emission_class"] = df.loc[cond, "emission_class"].fillna(df["emission_class"].mode()[0])

In [244]:
df["emission_class"].value_counts(dropna=False)

Euro 6          14022
Euro 6d-TEMP     4149
Euro 6d          3250
Euro 5           3067
Euro 4           2324
Euro 3            774
Euro 2            473
Euro 1            429
Euro 6c           142
Name: emission_class, dtype: int64

In [246]:
simdi('emissions_sticker')

Column Name    :  emissions_sticker
----------------------------------------
Per_of_nulls   :  % 67.12
Num_of_nulls   :  19216
Num_of_uniques :  4
----------------------------------------
NaN               19216
4 (Green)          9230
1 (No sticker)      176
3 (Yellow)            6
2 (Red)               2
Name: emissions_sticker, dtype: int64

In [247]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["emissions_sticker"].mode())
            if mode != []:
                df.loc[cond, "emissions_sticker"] = df.loc[cond, "emissions_sticker"].fillna(df[cond]["emissions_sticker"].mode()[0])
            else:
                df.loc[cond, "emissions_sticker"] = df.loc[cond, "emissions_sticker"].fillna(df["emissions_sticker"].mode()[0])

In [248]:
df["emissions_sticker"].value_counts(dropna=False)

4 (Green)         28231
1 (No sticker)      391
3 (Yellow)            6
2 (Red)               2
Name: emissions_sticker, dtype: int64

In [250]:
simdi('comfort_&_convenience')

Column Name    :  comfort_&_convenience
----------------------------------------
Per_of_nulls   :  % 11.17
Num_of_nulls   :  3197
Num_of_uniques :  14438
----------------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                            3197
Air conditioning, Automatic climate control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                                              244
Air conditioning, Automatic climate control, Cruise control                                                                                                                                                                                                                                                                                                                                                     171
Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                              168
Air conditioning                                                                                                                                                                                                                                                                                                                                                                                                157
                                                                                                                                                                                                                                                                                                                                                                                                               ...
Armrest, Automatic climate control, 2 zones, Cruise control, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system                                                                                     1
Air conditioning, Armrest, Automatic climate control, Cruise control, Electric tailgate, Electrical side mirrors, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating                                               1
Armrest, Automatic climate control, 2 zones, Cruise control, Electrical side mirrors, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows       1
Armrest, Automatic climate control, 2 zones, Cruise control, Electrical side mirrors, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows           1
Air conditioning, Armrest, Cruise control, Electrical side mirrors, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Seat heating, Tinted windows                                                                                                                                                                                                         1
Name: comfort_&_convenience, Length: 14439, dtype: int64

In [251]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["comfort_&_convenience"].mode())
            if mode != []:
                df.loc[cond, "comfort_&_convenience"] = df.loc[cond, "comfort_&_convenience"].fillna(df[cond]["comfort_&_convenience"].mode()[0])
            else:
                df.loc[cond, "comfort_&_convenience"] = df.loc[cond, "comfort_&_convenience"].fillna(df["comfort_&_convenience"].mode()[0])

In [252]:
df["comfort_&_convenience"].isnull().sum()

0

In [261]:
df.head(1).T

                                                                         0
short_description                                                      CDi
make                                                         Mercedes-Benz
model                                                               A 160
location                 P.I. EL PALMAR C/FORJA 6,  11500 PUERTO DE SAN...
price(€)                                                             16950
body_type                                                         Compact
type                                                                 Used
doors                                                                5.000
country_version                                                      Spain
warranty                                                        24 months
mileage                                                         120200.000
first_registration                                                 06/2016
gearbox                                                             Manual
fuel_type                                                           Diesel
colour                                                               Black
paint                                                             Metallic
desc                     Cash price: 16950 euros, vehicle with maintena...
seller                                                              Dealer
seats                                                                5.000
power                                                               75.000
engine_size                                                        1595 cc
gears                                                                5.000
co₂-emissions                                             126 g/km (comb.)
manufacturer_colour                                         Grijs metallic
drivetrain                                                          Front
cylinders                                                            4.000
fuel_consumption                                                       5.4
empty_weight                                                       1270 kg
general_inspection                                                     New
emission_class                                                      Euro 6
emissions_sticker                                           1 (No sticker)
upholstery_colour                                                    Black
upholstery                                                           Cloth
production_date                                                 2015-01-01
energy_efficiency_class                                               A+++
co₂-efficiency           Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience    Air conditioning, Armrest, Automatic climate c...
entertainment_&_media                          Bluetooth, CD player, Radio
safety_&_security        ABS, Adaptive Cruise Control, Alarm system, Dr...
extras                                                        Alloy wheels
country                                                              Spain
make_model                                           Mercedes-Benz  A 160
age                                                                  7.000

In [254]:
simdi('entertainment_&_media')

Column Name    :  entertainment_&_media
----------------------------------------
Per_of_nulls   :  % 17.42
Num_of_nulls   :  4986
Num_of_uniques :  1944
----------------------------------------
NaN                                                                                                                                                                        4986
Bluetooth, USB                                                                                                                                                              753
Bluetooth                                                                                                                                                                   665
On-board computer                                                                                                                                                           662
CD player, On-board computer, Radio                                                                                                                                         644
                                                                                                                                                                           ...
Android Auto, Apple CarPlay, Bluetooth, Digital cockpit, Digital radio, Induction charging for smartphones, On-board computer, Radio, Sound system, WLAN / WiFi hotspot       1
Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Integrated music streaming, On-board computer, Sound system, USB, WLAN / WiFi hotspot             1
Digital cockpit, Digital radio, On-board computer, Radio                                                                                                                      1
Android Auto, Apple CarPlay, Digital radio, On-board computer, Radio, Sound system, USB, WLAN / WiFi hotspot                                                                  1
Hands-free equipment, Integrated music streaming, On-board computer, Radio, USB                                                                                               1
Name: entertainment_&_media, Length: 1945, dtype: int64

In [255]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["entertainment_&_media"].mode())
            if mode != []:
                df.loc[cond, "entertainment_&_media"] = df.loc[cond, "entertainment_&_media"].fillna(df[cond]["entertainment_&_media"].mode()[0])
            else:
                df.loc[cond, "entertainment_&_media"] = df.loc[cond, "entertainment_&_media"].fillna(df["entertainment_&_media"].mode()[0])

In [256]:
df["entertainment_&_media"].isnull().sum()

0

In [258]:
simdi('safety_&_security')

Column Name    :  safety_&_security
----------------------------------------
Per_of_nulls   :  % 11.23
Num_of_nulls   :  3215
Num_of_uniques :  12549
----------------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3215
Isofix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        380
ABS, Central door lock, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                             328
ABS, Central door lock, Driver-side airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                                                                                                         125
ABS, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Isofix, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                                                     121
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ...
Daytime running lights, Emergency brake assistant, Fog lights, Isofix, LED Daytime Running Lights, Lane departure warning system, Power steering, Tire pressure monitoring system                                                                                                                                                                                                                                                                                                                                               1
ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Immobilizer, Isofix, LED Headlights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                1
ABS, Driver-side airbag, Electronic stability control, Emergency brake assistant, Immobilizer, LED Daytime Running Lights, Passenger-side airbag, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                                1
ABS, Blind spot monitor, Central door lock, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency system, Fog lights, Full-LED headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition       1
ABS, Alarm system, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                              1
Name: safety_&_security, Length: 12550, dtype: int64

In [259]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["safety_&_security"].mode())
            if mode != []:
                df.loc[cond, "safety_&_security"] = df.loc[cond, "safety_&_security"].fillna(df[cond]["safety_&_security"].mode()[0])
            else:
                df.loc[cond, "safety_&_security"] = df.loc[cond, "safety_&_security"].fillna(df["safety_&_security"].mode()[0])

In [260]:
df["safety_&_security"].isnull().sum()

0

In [262]:
simdi('desc')

Column Name    :  desc
----------------------------------------
Per_of_nulls   :  % 4.32
Num_of_nulls   :  1236
Num_of_uniques :  22741
----------------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1236
Exact information on the standard equipment, can be found on our homepage., We are happy to take your current vehicle back!, The seller assumes no liability for tip and data transfer error.,  Check. , All information in the advertisements are non-binding and without guarantee. , Dacia Jogger TCE 110 Extreme+ 7-seater , Special Equipment , City Package ,- Electrical Parking Brake ,- Increased center console  , - parking aid at the front and back, - reversing camera, - dead angle warning, seat heating for front seats, automatic climate automatic, Darkened slices at the back , 7-seater , standard equipment , Eco LED headlights , Reserverad , emergency brake assistant , eco-mode , 12V socket , folding tables for second row of seats , el. Parking brake , Sun visors with make-up mirror , front passenger aperture with make-up mirror , drivers seat height adjustable , steering wheel height and longitudinal adjustable , rear seating bench 60/40 foldable , power steering , central locking , El. Window lifter at the front and back , el. Side mirror , Consistent central locking , arm back , steering wheel in a leather look with multifunction , roofing ring modular , light metal rims in black with summer tires , tire pressure control , Dacia Media NAV MultimediaSystem , Dab-Radio , MP3 capable , Bluetooth , USB connection , TouchCreen , CarPlay , Android Auto , Voice Panel , Navigation System , Tempomat, hands-free contact, On-board computer check- Control , speed limitation system , incl. Guarantee , Care magazine , Nichsraucher-Fhrz. , ABS , ESP , Traction control , E10 , particle filter , rain sensor , el. Ride-to-move-up , Start/Stop automatic , emergency call system , isofi , x , fog lights , LED daylight , daytime running light , Lichtensor , driver airbag , passenger Airbag , door/side airbag , Vehicle is expected to be available in 6-8 weeks! , 5-door, daily registration, condition, accident: accident-free , immediately available , See More ]                                                                                                                                                                                                                                                                                                                                                                                                                                   51
Ref. 4236LFG , occasionPlus , Only this month best guaranteed price , Buy with total confidence - 15 days or 1000 kms of test , OCASIONPLUS - Nº1 QUALITY/PRICE , 5000 cars - 50 centers throughout the peninsula , Choose your car and take it to your province , Until € 2350 discount on this car , We also do custom financing, ask us !! , Outstanding equipment: panoramic roof, leather upholstery, assistant parking, browser, automatic lighting lighting, button start, automatic start/stop, speed control, multifunction steering wheel, bluetooth, air conditioning (air conditioning), traction control, alloy wheels (18 "). ,- Total guarantee 1 year, with national coverage, expandable to 24 months. ,- Certificate of kilometers and absence of structural blows. Any car in any center for € 100 ,- Open Sunday and Fes tivos. , Extras, User selected equipment, - 18 " alloy wheels,- panoramic roof ,- browser ,- automatic start/stop ,- control of Speed ​​,- Multifunction steering wheel ,- Bluetooth ,- Traction control ,- climatizer ,- alloy wheels ,- air conditioning ,- leather upholstery ,- assistant of Parking ,- Automatic lighting of headlights, - Start by button, see more]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               34
Cash price: 15200 euros, ref. 6710kjs , "Ocasionplus , Only this month best guaranteed price , Buy with total confidence - 15 days or 1000 km of test , OCASIONPLUS - Nº1 QUALITY/PRICE , 5000 COVERS - 50 CENTERS throughout the Peninsula , Choose your car and we take it to your province , Until € 1382 discount in this car , Financed offer price: € 13818 (€ 202/month) Finishing the totality to a minimum term of 60 months , Cash price: € 15200 We also make custom financing, ask us !! ", outstanding equipment: LED rear headlights, Bluetooth, button for button, air conditioning (air conditioner), isofix, alloy wheels (16") . ,- National Car. ,- Total guarantee 1 year, with national coverage, expandable to 24 months. ,- Certificate of kilometers and absence of structural blows. . Train it now on occasionPlus.com ,- We deliver any car in any center for € 100 , Open Sunday and holidays. , Extra S , User-selected outstanding equipment ,- Bluetooth ,- Climatizer ,- Alloy wheels ,- Air conditioning ,- 16 "alloy wheels" ,- LED rear headlights ,- ISOFI , X- Start by button , Financing conditions , Ocasionplus , Only this month best guaranteed price , Buy with total confidence- 15 days or 1000 km test  , OcasionPlus - Nº1 Quality/Price, 5000 cars - 50 centers throughout the Peninsula, Choose your car and take it to your province, Until € 1382 discount on this car, Price offer offer funded : € 13818 (€ 202/month) Finishing the totality to a minimum term of 60 months , Cash price: € 15200 In addition we make custom financing, ask us !! ", see more]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 34
Cash price: 15400 euros, ref. 7958jfk , "The coolest prices of summer , 5000 cars with a discount of up to € 6000’, Only until the end of the month, premieres vacation with your new car, Ocasionplus - No. 1 Quality/ Quality/ Price , 47 Centers throughout the Peninsula, Choose your car and take it to your province, Up to € 1007 discount in this car, Financed offer price: € 14393 (€ 298/month) Finishing The totality to a minimum term of 60 months , Cash price: € 15400 In addition we make custom financing, ask us !! ", Outstanding equipment: Leather-Tela upholstery, Automatic Start/Stop, button for button, automatic ignition of headlights, multifunction steering wheel, isofix, bluetooth, speed control, pneumatic pressure sensor, air conditioning (air conditioning), radio, alloy wheels (16 "). ,- national car, maintenance history. ,- - Total guarantee 1 year, with national coverage, expandable to 24 months. ,- certificate of kilometers and absence of blows is Tructural. ,- We overvalue your car in change operations. Take it now on occasionPlus.com ,- We deliver any car in any center for € 100 , Open Sunday and holidays. , - Bluetooth, - Climatizer, - Alloy wheels,- air conditioning ,- 16 " alloy wheels, - isofi, x- automatic lighting of headlights,- - Pneumatic pressure sensor , financing conditions, "The freshest prices of summer, 5000 cars with discount of up to € 6000’, only until the end of the month come to occasion, premieres vacation with Your new car , OCCASPLUS - Nº1 QUALITY/PRICE , 47 Centers throughout the Peninsula, Choose your car and take it to your province, Up to € 1007 discount on this car, Offer offering price Financed: € 14393 (€ 298/month) Finishing the totality to a minimum term of 60 months , Cash price: € 15400 In addition we make custom financing, ask us !! ", see more]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...
With Peugeot connection guarantee by 2024]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
"! Cdata \ Xa0The Options: 3 rear safety belts 3 points with effort limiter, ABS (wheel anti -lock), rear central armrest with ski hatch, graphics display, emergency braking assistance (AFU) , Sound and graphic help with rear parking, Automatic air conditioning Bizone + rear diffuser, driver and passenger front airbags (neutralizable passenger), front side and curtains, automatic ignition of distress lights in the event of strong deceleration, rings of grasp in the Coffee for net, electronic coded anti-starting, strong back headrest (x 3) adjustable in height, front headrest 2 axes with height adjustment, foldable rear bench (2/3 -1/3) with MODULARDUAL MAGIC Flat, belts before safety with pyrotechnic pretension adjustable in height with effort limiter, front central console with ventilated storage of 13.5L, dynamic stability control (ESP), under-inflation detectors, automatic unlocking of s Doors in the event of a shock, variable assistance electro-hydraulic steering, rear wander with variable intermittent, ISOFIX fixings (with rear side squares), automatic electrical parking brake + sloping start assistance, grip control, temperature indicator Outdoor, 16 Isara alloy rims, Electric front and rear front and rear lift, sequential with anti-pinch, heated rear bezel, mute rear rear bezel, Lighting pack, visibility pack, acoustic tinted windshield, Peugeot Connect SOS & Assistance, front central ceiling light with 2 reading spots + chest light, 3 -position chest floor, chaplain pockets on the back of the front seats, doors of gate doors and paint mirror boards, 12V socket (x3): at the front , at the rear and in the trunk, front fog lights, LED rear projectors, front projectors incorporating daytime fires and LED indicators, regulator E t speed limiter, electronic braking distributor REF, electrical exterior mirrors and degiver with repeater, checkout shell, “cake” emergency wheel, drivers seat with lumbar adjustment, height -adjustable drivers seat, front passenger seat adjustable in height, witnesses Non closing of all safety belts with rear outlet alert, storage hatch under floor in row 2, automatic locking of all the opening, rolling, central locking with two high frequency remote controls, leather crust steering wheel, adjustable in height and In depth, lower back shutter, WIP Nav PUS, WIP Sound Radio CD MP3 with auxiliary jack]] ", See More]       1

In [263]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["desc"].mode())
            if mode != []:
                df.loc[cond, "desc"] = df.loc[cond, "desc"].fillna(df[cond]["desc"].mode()[0])
            else:
                df.loc[cond, "desc"] = df.loc[cond, "desc"].fillna(df["desc"].mode()[0])

In [264]:
df["desc"].isnull().sum()

0

In [265]:
print(df.isna().any())

short_description           True
make                       False
model                      False
location                   False
price(€)                   False
body_type                  False
type                       False
doors                      False
country_version             True
warranty                    True
mileage                    False
first_registration          True
gearbox                     True
fuel_type                   True
colour                      True
paint                      False
desc                       False
seller                     False
seats                      False
power                      False
engine_size                False
gears                      False
co₂-emissions              False
manufacturer_colour        False
drivetrain                 False
cylinders                  False
fuel_consumption           False
empty_weight               False
general_inspection         False
emission_class             False
emissions_sticker          False
upholstery_colour          False
upholstery                 False
production_date             True
energy_efficiency_class    False
co₂-efficiency             False
comfort_&_convenience      False
entertainment_&_media      False
safety_&_security          False
extras                     False
country                    False
make_model                 False
age                        False
dtype: bool

In [267]:
simdi('short_description')

Column Name    :  short_description
----------------------------------------
Per_of_nulls   :  % 0.74
Num_of_nulls   :  213
Num_of_uniques :  20946
----------------------------------------
NaN                                                   213
D2 Momentum 120                                        88
D2 Kinetic 120                                         87
Cabrio 1.4T S&S Excellence                             85
Extreme+ 7-Sitzer TCe 110                              57
                                                     ...
PureTech  EAT8 Allure Pack...DISP. PER NOLEGGIO         1
BlueHDi 130 S&S EAT8 Business                           1
2.0 BlueHDi 180ch S\u0026S GT Line EAT8                 1
1.2 PureTech Première AUT. NAVI PANO                    1
2.9 Executive G. NETTE AUTO! LEER! NAVI! CRUISE! L      1
Name: short_description, Length: 20947, dtype: int64

In [268]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["short_description"].mode())
            if mode != []:
                df.loc[cond, "short_description"] = df.loc[cond, "short_description"].fillna(df[cond]["short_description"].mode()[0])
            else:
                df.loc[cond, "short_description"] = df.loc[cond, "short_description"].fillna(df["short_description"].mode()[0])

In [269]:
df["short_description"].isnull().sum()

0

In [271]:
simdi('country_version')

Column Name    :  country_version
----------------------------------------
Per_of_nulls   :  % 0.12
Num_of_nulls   :  35
Num_of_uniques :  10
----------------------------------------
Germany             12635
Spain                5686
Netherlands          2857
Italy                2482
Belgium              2346
France               1533
Austria              1053
NaN                    35
 Germany                1
 Luxembourg             1
 European Union         1
Name: country_version, dtype: int64

In [272]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["country_version"].mode())
            if mode != []:
                df.loc[cond, "country_version"] = df.loc[cond, "country_version"].fillna(df[cond]["country_version"].mode()[0])
            else:
                df.loc[cond, "country_version"] = df.loc[cond, "country_version"].fillna(df["country_version"].mode()[0])

In [273]:
df["country_version"].isnull().sum()

0

In [274]:
simdi('warranty')

Column Name    :  warranty
----------------------------------------
Per_of_nulls   :  % 44.87
Num_of_nulls   :  12846
Num_of_uniques :  65
----------------------------------------
NaN             12846
 12 months       9545
 Yes             2319
 24 months       1515
 60 months        968
 6 months         398
 36 months        257
 3 months         185
 0 months         133
 48 months         78
 84 months         47
 72 months         40
 13 months         22
 8 months          19
 18 months         15
 1 months          15
 15 months         13
 14 months         13
 16 months         13
 30 months         12
 34 months         11
 21 months         11
 33 months         11
 32 months          9
 20 months          9
 23 months          9
 19 months          9
 17 months          9
 35 months          8
 28 months          8
 50 months          6
 22 months          6
 42 months          5
 31 months          4
 26 months          4
 52 months          4
 47 months          4
 9 months           4
 25 months          3
 58 months          3
 11 months          3
 27 months          3
 45 months          2
 53 months          2
 10 months          2
 57 months          2
 51 months          2
 29 months          2
 2 months           2
 80 months          2
 90 months          2
 7 months           2
 46 months          1
 117 months         1
 43 months          1
 65 months          1
 39 months          1
 142 months         1
 110 months         1
 37 months          1
 49 months          1
 55 months          1
 99 months          1
 122 months         1
 44 months          1
 4 months           1
Name: warranty, dtype: int64

In [278]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["warranty"].mode())
            if mode != []:
                df.loc[cond, "warranty"] = df.loc[cond, "warranty"].fillna(df[cond]["warranty"].mode()[0])
            else:
                df.loc[cond, "warranty"] = df.loc[cond, "warranty"].fillna(df["warranty"].mode()[0])

In [279]:
simdi('first_registration')

Column Name    :  first_registration
----------------------------------------
Per_of_nulls   :  % 0.01
Num_of_nulls   :  2
Num_of_uniques :  655
----------------------------------------
08/2022    454
06/2022    428
05/2019    420
06/2019    418
07/2019    416
          ...
06/1967      1
06/1980      1
09/1970      1
06/1963      1
10/1979      1
Name: first_registration, Length: 656, dtype: int64

In [280]:
simdi('gearbox')

Column Name    :  gearbox
----------------------------------------
Per_of_nulls   :  % 0.87
Num_of_nulls   :  248
Num_of_uniques :  3
----------------------------------------
Manual            17023
Automatic         11287
NaN                 248
Semi-automatic       72
Name: gearbox, dtype: int64

In [281]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["gearbox"].mode())
            if mode != []:
                df.loc[cond, "gearbox"] = df.loc[cond, "gearbox"].fillna(df[cond]["gearbox"].mode()[0])
            else:
                df.loc[cond, "gearbox"] = df.loc[cond, "gearbox"].fillna(df["gearbox"].mode()[0])

In [282]:
simdi('fuel_type')

Column Name    :  fuel_type
----------------------------------------
Per_of_nulls   :  % 6.24
Num_of_nulls   :  1787
Num_of_uniques :  7
----------------------------------------
Benzine                     17547
Diesel                       8727
NaN                          1787
LPG/CNG                       359
Electric                      188
Others (Particle filter)       16
Ethanol                         3
Hydrogen                        3
Name: fuel_type, dtype: int64

In [283]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["fuel_type"].mode())
            if mode != []:
                df.loc[cond, "fuel_type"] = df.loc[cond, "fuel_type"].fillna(df[cond]["fuel_type"].mode()[0])
            else:
                df.loc[cond, "fuel_type"] = df.loc[cond, "fuel_type"].fillna(df["fuel_type"].mode()[0])

In [284]:
simdi('colour')

Column Name    :  colour
----------------------------------------
Per_of_nulls   :  % 6.02
Num_of_nulls   :  1724
Num_of_uniques :  14
----------------------------------------
Black     6473
Grey      5998
White     5185
Blue      3478
Red       2242
NaN       1724
Silver    1622
Green      450
Brown      437
Orange     288
Beige      278
Yellow     230
Violet      98
Bronze      65
Gold        62
Name: colour, dtype: int64

In [285]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["colour"].mode())
            if mode != []:
                df.loc[cond, "colour"] = df.loc[cond, "colour"].fillna(df[cond]["colour"].mode()[0])
            else:
                df.loc[cond, "colour"] = df.loc[cond, "colour"].fillna(df["colour"].mode()[0])

In [292]:
print(df.isna().any())

short_description          False
make                       False
model                      False
location                   False
price(€)                   False
body_type                  False
type                       False
doors                      False
country_version            False
warranty                   False
mileage                    False
first_registration         False
gearbox                    False
fuel_type                  False
colour                     False
paint                      False
desc                       False
seller                     False
seats                      False
power                      False
engine_size                False
gears                      False
co₂-emissions              False
manufacturer_colour        False
drivetrain                 False
cylinders                  False
fuel_consumption           False
empty_weight               False
general_inspection         False
emission_class             False
emissions_sticker          False
upholstery_colour          False
upholstery                 False
production_date            False
energy_efficiency_class    False
co₂-efficiency             False
comfort_&_convenience      False
entertainment_&_media      False
safety_&_security          False
extras                     False
country                    False
make_model                 False
age                        False
dtype: bool

In [287]:
simdi('first_registration')

Column Name    :  first_registration
----------------------------------------
Per_of_nulls   :  % 0.01
Num_of_nulls   :  2
Num_of_uniques :  655
----------------------------------------
08/2022    454
06/2022    428
05/2019    420
06/2019    418
07/2019    416
          ...
06/1967      1
06/1980      1
09/1970      1
06/1963      1
10/1979      1
Name: first_registration, Length: 656, dtype: int64

In [288]:
simdi('production_date')

Column Name    :  production_date
----------------------------------------
Per_of_nulls   :  % 0.01
Num_of_nulls   :  2
Num_of_uniques :  81
----------------------------------------
2018-01-01    3775
2021-01-01    3367
2017-01-01    3042
2020-01-01    2728
2019-01-01    2580
2016-01-01    2045
2015-01-01    1349
2022-01-01    1190
2014-01-01    1128
2013-01-01     786
2011-01-01     666
2012-01-01     650
2010-01-01     600
2009-01-01     510
2007-01-01     479
2006-01-01     478
2008-01-01     393
2005-01-01     330
2004-01-01     275
2003-01-01     247
2001-01-01     191
2000-01-01     183
2002-01-01     177
1999-01-01     173
1998-01-01     102
1997-01-01      95
1995-01-01      83
1996-01-01      74
1994-01-01      71
1991-01-01      71
1993-01-01      69
1992-01-01      53
1990-01-01      47
1966-01-01      44
1989-01-01      43
1972-01-01      38
1965-01-01      34
1986-01-01      34
1987-01-01      27
1964-01-01      27
1967-01-01      26
1988-01-01      25
1977-01-01      24
1968-01-01      21
1970-01-01      21
1978-01-01      21
1982-01-01      18
1971-01-01      18
1969-01-01      16
1983-01-01      16
1984-01-01      15
1985-01-01      13
1974-01-01      13
1963-01-01      12
1975-01-01      12
1979-01-01      10
1961-01-01       9
1976-01-01       9
1973-01-01       9
1962-01-01       7
1959-01-01       6
1954-01-01       6
1957-01-01       6
1980-01-01       6
1981-01-01       6
1953-01-01       4
1929-01-01       3
1931-01-01       3
NaN              2
1955-01-01       2
1936-01-01       2
1958-01-01       2
1899-01-01       2
1960-01-01       2
1952-01-01       2
1933-01-01       1
2024-01-01       1
1946-01-01       1
1956-01-01       1
2202-01-01       1
1928-01-01       1
1950-01-01       1
Name: production_date, dtype: int64

In [289]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["production_date"].mode())
            if mode != []:
                df.loc[cond, "production_date"] = df.loc[cond, "production_date"].fillna(df[cond]["production_date"].mode()[0])
            else:
                df.loc[cond, "production_date"] = df.loc[cond, "production_date"].fillna(df["production_date"].mode()[0])

In [290]:
simdi('production_date')

Column Name    :  production_date
----------------------------------------
Per_of_nulls   :  % 0.0
Num_of_nulls   :  0
Num_of_uniques :  81
----------------------------------------
2018-01-01    3775
2021-01-01    3367
2017-01-01    3042
2020-01-01    2729
2019-01-01    2581
2016-01-01    2045
2015-01-01    1349
2022-01-01    1190
2014-01-01    1128
2013-01-01     786
2011-01-01     666
2012-01-01     650
2010-01-01     600
2009-01-01     510
2007-01-01     479
2006-01-01     478
2008-01-01     393
2005-01-01     330
2004-01-01     275
2003-01-01     247
2001-01-01     191
2000-01-01     183
2002-01-01     177
1999-01-01     173
1998-01-01     102
1997-01-01      95
1995-01-01      83
1996-01-01      74
1994-01-01      71
1991-01-01      71
1993-01-01      69
1992-01-01      53
1990-01-01      47
1966-01-01      44
1989-01-01      43
1972-01-01      38
1986-01-01      34
1965-01-01      34
1987-01-01      27
1964-01-01      27
1967-01-01      26
1988-01-01      25
1977-01-01      24
1968-01-01      21
1970-01-01      21
1978-01-01      21
1982-01-01      18
1971-01-01      18
1969-01-01      16
1983-01-01      16
1984-01-01      15
1985-01-01      13
1974-01-01      13
1963-01-01      12
1975-01-01      12
1979-01-01      10
1961-01-01       9
1976-01-01       9
1973-01-01       9
1962-01-01       7
1954-01-01       6
1959-01-01       6
1957-01-01       6
1980-01-01       6
1981-01-01       6
1953-01-01       4
1929-01-01       3
1931-01-01       3
1955-01-01       2
1936-01-01       2
1958-01-01       2
1960-01-01       2
1952-01-01       2
1899-01-01       2
2202-01-01       1
1933-01-01       1
2024-01-01       1
1950-01-01       1
1946-01-01       1
1956-01-01       1
1928-01-01       1
Name: production_date, dtype: int64

In [291]:

for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
            cond = (df["make_model"]==group1) & (df["body_type"]==group2)
            mode = list(df[cond]["first_registration"].mode())
            if mode != []:
                df.loc[cond, "first_registration"] = df.loc[cond, "first_registration"].fillna(df[cond]["first_registration"].mode()[0])
            else:
                df.loc[cond, "first_registration"] = df.loc[cond, "first_registration"].fillna(df["first_registration"].mode()[0])

In [293]:
df.to_csv("autodolu.csv", index=False)

In [294]:
df.head(3).T

,0,1,2
short_description,CDi,350+,S 4Matic+ 8G-DCT
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz
model,A 160,EQE 350,A 45 AMG
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8..."
price(€),16950,80900,69900
body_type,Compact,Compact,Compact
type,Used,Pre-registered,Used
doors,5.000,4.000,5.000
country_version,Spain,Spain,Spain
warranty,24 months,24 months,12 months
mileage,120200.000,5000.000,18900.000
first_registration,06/2016,06/2022,07/2020
gearbox,Manual,Automatic,Automatic
fuel_type,Diesel,Electric,Benzine
colour,Black,Black,Grey
paint,Metallic,Metallic,Metallic
desc,"Cash price: 16950 euros, vehicle with maintena...","Cash price: 88900 euros, Auto Oja S.A. - Offic...","Gray Manufakur Mountingrau Magno, Line/Style A..."
seller,Dealer,Dealer,Dealer
seats,5.000,5.000,5.000
power,75.000,215.000,310.000
engine_size,1595 cc,1 cc,1991 cc
gears,5.000,6.000,8.000
co₂-emissions,126 g/km (comb.),0 g/km (comb.),162 g/km (comb.)
manufacturer_colour,Grijs metallic,Negro Obsidiana,Mountaingrau magno
drivetrain,Front,Front,4WD
cylinders,4.000,4.000,4.000
fuel_consumption,5.4,5,8.4
empty_weight,1270 kg,1395 kg,1555 kg
general_inspection,New,New,New
emission_class,Euro 6,Euro 6,Euro 6
emissions_sticker,1 (No sticker),4 (Green),4 (Green)
upholstery_colour,Black,Black,Black
upholstery,Cloth,Leather,Leather
production_date,2015-01-01,2021-01-01,2020-01-01
energy_efficiency_class,A+++,A+++,C
co₂-efficiency,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...,Calculated on basis of measured CO₂-emissions ...
comfort_&_convenience,"Air conditioning, Armrest, Automatic climate c...","Air conditioning, Automatic climate control, E...","Air conditioning, Electrical side mirrors, Mul..."
entertainment_&_media,"Bluetooth, CD player, Radio","Bluetooth, USB","Bluetooth, CD player, MP3, USB"
safety_&_security,"ABS, Adaptive Cruise Control, Alarm system, Dr...",Isofix,"ABS, Central door lock, Driver-side airbag, El..."
extras,Alloy wheels,Alloy wheels,Alloy wheels
country,Spain,Spain,Spain
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350,Mercedes-Benz A 45 AMG
age,7.000,1.000,2.000